-- SELL2AI isolated Supabase schema
-- Apply only to the dedicated SELL2AI project.

create extension if not exists pgcrypto;

create table if not exists public.stores (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  url text not null,
  domain text,
  platform text,
  latest_score integer check (latest_score between 0 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, url)
);

create table if not exists public.scans (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  store_id uuid not null references public.stores(id) on delete cascade,
  scan_id text not null,
  score integer not null check (score between 0 and 100),
  report jsonb not null,
  created_at timestamptz not null default now(),
  unique (user_id, scan_id)
);

create table if not exists public.buyer_tests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  store_id uuid not null references public.stores(id) on delete cascade,
  query text not null check (char_length(query) between 1 and 2000),
  result jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  store_id uuid references public.stores(id) on delete set null,
  type text not null check (type in ('scanner_accuracy','missing_feature','buyer_test','fix_pack','pricing','general')),
  rating integer not null check (rating between 1 and 5),
  message text not null check (char_length(message) between 1 and 5000),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  stripe_customer_id text unique,
  stripe_subscription_id text unique,
  plan text not null default 'free' check (plan in ('free','starter','growth','agency')),
  status text not null default 'inactive',
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  updated_at timestamptz not null default now()
);

create index if not exists scans_user_store_created_idx
  on public.scans (user_id, store_id, created_at desc);

create index if not exists buyer_tests_user_store_created_idx
  on public.buyer_tests (user_id, store_id, created_at desc);

create index if not exists feedback_created_idx
  on public.feedback (created_at desc);

alter table public.stores enable row level security;
alter table public.scans enable row level security;
alter table public.buyer_tests enable row level security;
alter table public.feedback enable row level security;
alter table public.subscriptions enable row level security;

drop policy if exists "stores_select_own" on public.stores;
create policy "stores_select_own"
on public.stores for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "stores_insert_own" on public.stores;
create policy "stores_insert_own"
on public.stores for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "stores_update_own" on public.stores;
create policy "stores_update_own"
on public.stores for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "stores_delete_own" on public.stores;
create policy "stores_delete_own"
on public.stores for delete
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "scans_select_own" on public.scans;
create policy "scans_select_own"
on public.scans for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "scans_insert_own_store" on public.scans;
create policy "scans_insert_own_store"
on public.scans for insert
to authenticated
with check (
  (select auth.uid()) = user_id
  and exists (
    select 1 from public.stores s
    where s.id = store_id and s.user_id = (select auth.uid())
  )
);

drop policy if exists "buyer_tests_select_own" on public.buyer_tests;
create policy "buyer_tests_select_own"
on public.buyer_tests for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "buyer_tests_insert_own_store" on public.buyer_tests;
create policy "buyer_tests_insert_own_store"
on public.buyer_tests for insert
to authenticated
with check (
  (select auth.uid()) = user_id
  and exists (
    select 1 from public.stores s
    where s.id = store_id and s.user_id = (select auth.uid())
  )
);

drop policy if exists "feedback_select_own" on public.feedback;
create policy "feedback_select_own"
on public.feedback for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "feedback_insert_own" on public.feedback;
create policy "feedback_insert_own"
on public.feedback for insert
to authenticated
with check (
  (select auth.uid()) = user_id
  and (
    store_id is null
    or exists (
      select 1 from public.stores s
      where s.id = store_id and s.user_id = (select auth.uid())
    )
  )
);

drop policy if exists "subscriptions_select_own" on public.subscriptions;
create policy "subscriptions_select_own"
on public.subscriptions for select
to authenticated
using ((select auth.uid()) = user_id);

grant select, insert, update, delete on public.stores to authenticated;
grant select, insert on public.scans to authenticated;
grant select, insert on public.buyer_tests to authenticated;
grant select, insert on public.feedback to authenticated;
grant select on public.subscriptions to authenticated;

grant all on public.stores, public.scans, public.buyer_tests, public.feedback, public.subscriptions to service_role;
grant usage, select on all sequences in schema public to authenticated, service_role;
